/**
 * Represents a single step in the multi-step plan generated by the AI.
 */
export interface PlanStep {
  agent: "RAG" | "NL2SQL" | "CodeExecution" | string;
  query: string;
  context: Record<string, any>;
}

/**
 * Represents the state and output of an agent executing a single plan step.
 * This is the primary state object we'll use to render the agent's progress.
 */
export interface AgentStep {
  index: number;
  agent: string;
  query: string;
  status: "pending" | "running" | "completed" | "error";
  output?: any; // Can be text, a table preview, etc.
  code?: {
    language: "sql" | "python";
    code: string;
  };
  error?: string;
}

/**
 * This object holds all the live data for a single, streaming assistant response.
 * We'll store this in state and update it as new events arrive.
 */
export interface AssistantTurn {
  id: string;
  plan: PlanStep[] | null;
  agentSteps: AgentStep[];
  finalResponse: string | null;
  isComplete: boolean;
  error?: string;
}
